export const chapters = [
  { id: 1, title: "The Swami Gimmick", description: "Mastering the art of the nail writer and related tools to secretly inscribe information while maintaining the appearance of genuine psychic ability.", color: "from-pink-500 to-purple-600", shadow: "shadow-pink-500/50", border: "border-pink-500/30" },
  { id: 2, title: "Pellets and Billets", description: "Techniques for handling folded papers containing spectators' thoughts, enabling the mentalist to read sealed information with deceptive ease.", color: "from-cyan-400 to-blue-600", shadow: "shadow-cyan-400/50", border: "border-cyan-400/30" },
  { id: 3, title: "Book Tests", description: "Methods for apparently reading any page from any book chosen by a spectator, one of mentalism's most classic and powerful demonstrations.", color: "from-yellow-400 to-orange-500", shadow: "shadow-yellow-400/50", border: "border-yellow-400/30" },
  { id: 4, title: "Predictions", description: "The art of foretelling future events before they happen, covering sealed envelopes, boxes, and elaborate presentational frameworks.", color: "from-green-400 to-emerald-600", shadow: "shadow-green-400/50", border: "border-green-400/30" },
  { id: 5, title: "Blindfold Work", description: "Performing feats of apparent clairvoyance while demonstrably blindfolded, including driving cars and reading objects while visually impaired.", color: "from-purple-500 to-indigo-600", shadow: "shadow-purple-500/50", border: "border-purple-500/30" },
  { id: 6, title: "Billets", description: "Advanced billet work including one-ahead systems, center tears, and the complete range of billet switching and reading techniques.", color: "from-rose-400 to-red-600", shadow: "shadow-rose-400/50", border: "border-rose-400/30" },
  { id: 7, title: "Two Person Telepathy", description: "Codes, systems, and stagecraft for presenting a convincing mind-reading act with a partner across any distance or condition.", color: "from-blue-500 to-indigo-700", shadow: "shadow-blue-500/50", border: "border-blue-500/30" },
  { id: 8, title: "Mnemonics and Mental Systems", description: "Memory systems, number codes, and mental calculation methods that give the mentalist superhuman recall and mathematical ability.", color: "from-teal-400 to-emerald-600", shadow: "shadow-teal-400/50", border: "border-teal-400/30" },
  { id: 9, title: "Card and Mathematical Effects", description: "Mentalism using playing cards and mathematical principles, where the math does the magic and the performer takes the credit.", color: "from-fuchsia-500 to-pink-700", shadow: "shadow-fuchsia-500/50", border: "border-fuchsia-500/30" },
  { id: 10, title: "Question and Answer Acts", description: "Running a complete question-and-answer demonstration for large audiences, covering all systems from one-ahead to electronic methods.", color: "from-amber-400 to-orange-600", shadow: "shadow-amber-400/50", border: "border-amber-400/30" },
  { id: 11, title: "Headline Acts", description: "Using newspaper predictions, current events, and sealed envelopes to create effects of genuine precognition for the press and public.", color: "from-cyan-500 to-teal-600", shadow: "shadow-cyan-500/50", border: "border-cyan-500/30" },
  { id: 12, title: "Psychometry", description: "Reading objects, photographs, and personal items to reveal their owner's past, present, and future through apparent psychic sensitivity.", color: "from-violet-500 to-purple-700", shadow: "shadow-violet-500/50", border: "border-violet-500/30" },
  { id: 13, title: "Publicity Stunts", description: "Large-scale public demonstrations designed to attract press coverage and establish the performer as a genuine psychic phenomenon.", color: "from-red-500 to-rose-700", shadow: "shadow-red-500/50", border: "border-red-500/30" }
];