export const chapters = [
  { id: 1, title: "The Swami Gimmick", description: "Mastering the art of the nail writer and related tools to secretly inscribe information while maintaining the appearance of genuine psychic ability.", color: "from-pink-500 to-purple-600", shadow: "shadow-pink-500/50", border: "border-pink-500/30" },
  { id: 2, title: "Pellets and Billets", description: "Techniques for handling folded papers containing spectators' thoughts, enabling the mentalist to read sealed information with deceptive ease.", color: "from-cyan-400 to-blue-600", shadow: "shadow-cyan-400/50", border: "border-cyan-400/30" },
  { id: 3, title: "Book Tests", description: "Methods for apparently reading any page from any book chosen by a spectator, one of mentalism's most classic and powerful demonstrations.", color: "from-yellow-400 to-orange-500", shadow: "shadow-yellow-400/50", border: "border-yellow-400/30" },
  { id: 4, title: "Predictions", description: "The art of foretelling future events before they happen, covering sealed envelopes, boxes, and elaborate presentational frameworks.", color: "from-green-400 to-emerald-600", shadow: "shadow-green-400/50", border: "border-green-400/30" },
  { id: 5, title: "Blindfold Work", description: "Performing feats of apparent clairvoyance while demonstrably blindfolded, including driving cars and reading objects while visually impaired.", color: "from-purple-500 to-indigo-600", shadow: "shadow-purple-500/50", border: "border-purple-500/30" },
  { id: 6, title: "Billets", description: "Advanced billet work including one-ahead systems, center tears, and the complete range of billet switching and reading techniques.", color: "from-rose-400 to-red-600", shadow: "shadow-rose-400/50", border: "border-rose-400/30" },
  { id: 7, title: "Two Person Telepathy", description: "Codes, systems, and stagecraft for presenting a convincing mind-reading act with a partner across any distance or condition.", color: "from-blue-500 to-indigo-700", shadow: "shadow-blue-500/50", border: "border-blue-500/30" },
  { id: 8, title: "Mnemonics and Mental Systems", description: "Memory systems, number codes, and mental calculation methods that give the mentalist superhuman recall and mathematical ability.", color: "from-teal-400 to-emerald-600", shadow: "shadow-teal-400/50", border: "border-teal-400/30" },
  { id: 9, title: "Card and Mathematical Effects", description: "Mentalism using playing cards and mathematical principles, where the math does the magic and the performer takes the credit.", color: "from-fuchsia-500 to-pink-700", shadow: "shadow-fuchsia-500/50", border: "border-fuchsia-500/30" },
  { id: 10, title: "Question and Answer Acts", description: "Running a complete question-and-answer demonstration for large audiences, covering all systems from one-ahead to electronic methods.", color: "from-amber-400 to-orange-600", shadow: "shadow-amber-400/50", border: "border-amber-400/30" },
  { id: 11, title: "Headline Acts", description: "Using newspaper predictions, current events, and sealed envelopes to create effects of genuine precognition for the press and public.", color: "from-cyan-500 to-teal-600", shadow: "shadow-cyan-500/50", border: "border-cyan-500/30" },
  { id: 12, title: "Psychometry", description: "Reading objects, photographs, and personal items to reveal their owner's past, present, and future through apparent psychic sensitivity.", color: "from-violet-500 to-purple-700", shadow: "shadow-violet-500/50", border: "border-violet-500/30" },
  { id: 13, title: "Publicity Stunts", description: "Large-scale public demonstrations designed to attract press coverage and establish the performer as a genuine psychic phenomenon.", color: "from-red-500 to-rose-700", shadow: "shadow-red-500/50", border: "border-red-500/30" },
];

export const books = [
  {
    id: "corinda",
    slug: "corinda",
    title: "Thirteen Steps to Mentalism",
    author: "Corinda",
    tag: "Mentalism Bible",
    description: "The definitive bible of mentalism — thirteen complete systems from the swami gimmick to publicity stunts. Every serious student starts here.",
    pdf: "/pdfs/corinda.pdf",
    color: "from-purple-500 to-indigo-700",
    glow: "rgba(139,92,246,0.5)",
    tagColor: "bg-purple-900/40 text-purple-300 border-purple-700/40",
    hasChapters: true,
  },
  {
    id: "annemann",
    slug: "annemann",
    title: "Practical Mental Magic",
    author: "Theodore Annemann",
    tag: "Classic Effects",
    description: "A masterwork from the golden age of mentalism — billets, book tests, predictions and the impossible made practical.",
    pdf: "/pdfs/annemann.pdf",
    color: "from-cyan-400 to-blue-600",
    glow: "rgba(34,211,238,0.4)",
    tagColor: "bg-cyan-900/40 text-cyan-300 border-cyan-700/40",
    hasChapters: false,
  },
  {
    id: "rowland",
    slug: "rowland",
    title: "The Full Facts Book of Cold Reading",
    author: "Ian Rowland",
    tag: "Cold Reading",
    description: "The complete technical manual for cold reading — every element from rainbow ruses to Barnum statements to win-win games.",
    pdf: "/pdfs/rowland.pdf",
    color: "from-emerald-400 to-teal-600",
    glow: "rgba(52,211,153,0.4)",
    tagColor: "bg-emerald-900/40 text-emerald-300 border-emerald-700/40",
    hasChapters: false,
  },
  {
    id: "ekman",
    slug: "ekman",
    title: "Telling Lies",
    author: "Paul Ekman",
    tag: "Deception Science",
    description: "The world's foremost authority on micro-expressions reveals the science of deceit — from clinical patients to presidential hearings.",
    pdf: "/pdfs/ekman.pdf",
    color: "from-rose-400 to-red-600",
    glow: "rgba(251,113,133,0.4)",
    tagColor: "bg-rose-900/40 text-rose-300 border-rose-700/40",
    hasChapters: false,
  },
  {
    id: "spy",
    slug: "spy",
    title: "Spy the Lie",
    author: "Houston, Floyd, Carnicero & Tennant",
    tag: "CIA Interrogation",
    description: "Former CIA officers reveal their field-tested lie-detection methodology honed in real high-stakes intelligence work.",
    pdf: "/pdfs/spy.pdf",
    color: "from-amber-400 to-orange-600",
    glow: "rgba(251,191,36,0.4)",
    tagColor: "bg-amber-900/40 text-amber-300 border-amber-700/40",
    hasChapters: false,
  },
  {
    id: "schafer",
    slug: "schafer",
    title: "The Like Switch",
    author: "Jack Schafer, Ph.D.",
    tag: "Rapport & Influence",
    description: "An ex-FBI behavioral analyst reveals the exact techniques used to make strangers trust and like you — without saying a word.",
    pdf: "/pdfs/schafer.pdf",
    color: "from-sky-400 to-blue-600",
    glow: "rgba(56,189,248,0.4)",
    tagColor: "bg-sky-900/40 text-sky-300 border-sky-700/40",
    hasChapters: false,
  },
  {
    id: "cialdini",
    slug: "cialdini",
    title: "Influence",
    author: "Robert B. Cialdini, Ph.D.",
    tag: "Persuasion",
    description: "Six universal principles of compliance that drive human behavior — the scientific bedrock beneath every successful mentalism presentation.",
    pdf: "/pdfs/cialdini.pdf",
    color: "from-yellow-400 to-amber-600",
    glow: "rgba(250,204,21,0.4)",
    tagColor: "bg-yellow-900/40 text-yellow-300 border-yellow-700/40",
    hasChapters: false,
  },
  {
    id: "navarro",
    slug: "navarro",
    title: "What Every Body Is Saying",
    author: "Joe Navarro",
    tag: "Body Language",
    description: "An ex-FBI agent's complete guide to reading nonverbal communication — the foundation of any convincing cold reading or mind-reading act.",
    pdf: "/pdfs/navarro.pdf",
    color: "from-green-400 to-emerald-600",
    glow: "rgba(74,222,128,0.4)",
    tagColor: "bg-green-900/40 text-green-300 border-green-700/40",
    hasChapters: false,
  },
  {
    id: "pease",
    slug: "pease",
    title: "The Definitive Book of Body Language",
    author: "Allan & Barbara Pease",
    tag: "Body Language",
    description: "The world's foremost expert on body language decodes every gesture, expression, and posture with practical precision.",
    pdf: "/pdfs/pease.pdf",
    color: "from-fuchsia-500 to-pink-600",
    glow: "rgba(232,121,249,0.4)",
    tagColor: "bg-fuchsia-900/40 text-fuchsia-300 border-fuchsia-700/40",
    hasChapters: false,
  },
];
